### ISSUE TITLE
It cannot support ACR122U-A9 on Windows

### ISSUE THREAD

**Issue by peter279k** [GoogleChrome/chrome-nfc#16]
I tried to connect device and ran sample chrome app but their Name,vendorId and productId did not displayed. I saw their vendorId and productId were same as ACR122U's.
What should I do?

**Comment by cyrus-za** [comment]
I have the same issue. Running on Windows 8.1 and installed the default drivers for the ACR122U-A9.

**Comment by tutchmedia** [comment]
I have this same issue - Has anyone found a solution?

**Comment by zyxzhsh** [comment]
好像A9就是不行 谁有解决办法？

**Comment by beaufortfrancois** [comment]
Can you confirm that you're all running Windows?
If that's the case, you might want to follow https://github.com/GoogleChrome/chrome-nfc/issues/3 discussion. 

- Try installing Zadig at http://zadig.akeo.ie/
- Run Zadig, 
- Plug your NFC Reader, select it, 
- Choose "libusb-win32", click on "Replace Driver" button,
- Unplug your NFC Reader
- Give another try to the _chrome.nfc_ library.

This trick just worked for me minutes ago on Window 8.1.

**Comment by tutchmedia** [comment]
Just tried your steps and after installing the "libusb-win32" driver and removing the device, when i plug it back in it doesn't do anything. Even the light doesn't come on.

Any other ideas?

**Comment by beaufortfrancois** [comment]
1. Can you tell me which version of Window you're running?

2. If you no longer see the red light up, I believe this means Windows is no longer taking control of the device, which is a good thing since it should let Chrome take over this device.

3. "It doesn't do anything" doesn't help me much. Do you run the sample app or do you run the library by yourself in a chrome app? 

4. Did you have a chance to try the ACR122U-A9 device on another device (MacOS, Linux, ChromeOS)?

**Comment by gregoryhenry** [comment]
Hey Francois,

Greg from Alliance Tech here. I just tried the Zadig 'fix' on my windows 7 64-bit machine with no luck. I tried running your IO app from last year with it after I replaced the driver with the 'libusb-win32' version and then I also tried it with this NFC Chrome extension, and still nothing.

It does show in my Windows Device Manager as a libusb-win32 device, FYI.

I will test it on the Pixel when it arrives and see if it works. I'll document my findings in this issue so we can have it for future reference.

Thanks for looking into this,

**Comment by gregoryhenry** [comment]
Hey Francois,

Me again. The ACR122U-A9 device works on Chrome OS using your sample app.

Thanks,

Greg

**Comment by jarios86** [comment]
Hi everyone!!

I use ACR122U-A9 and I have tried to test the sample app in chrome, but it doen't work. In the Device windows on the chome.nfc app, name, vendor ID and product ID are empties.

I have test this device from other apps and it works fine.

Could anyone help me?
Thanks,
Antonio

**Comment by jordaofranca** [comment]
Just tryed from ubuntu, and windows, and its not working.

**Comment by rene1997** [comment]
for me zadig works great on windows 10. After installation make sure the check-mark at
options> list all devices is on. And follow the steps of francios.
If you don't see the led after all, you can open the reader from your chrome application.

**Comment by shahbazali** [comment]
Any Update? I'm testing ACR122u-A9 on Windows10, its not working, i installed drivers as well as per mentioned above, still same problem.

Any Luck ?

**Comment by shahbazali** [comment]
anyone can tell me what is the difference between ACR122u & ACR122u-A9? 

Looking Forward,

**Comment by shahbazali** [comment]
Hi @beaufortfrancois 

Would you please help, how to get Card Type & UID ? in my business logic i wants to check either its a card or emulated phone? if its a card i need its UID, if its a phone i need NDEF for the Emulated Phone. 

Looking Forward.

**Comment by beaufortfrancois** [comment]
@shahbazali Can you file a separate issue for that please?
