### ISSUE TITLE
Question : Does it support Android Phone Nfc Feature ?

### ISSUE THREAD

**Issue by jmorille** [GoogleChrome/chrome-nfc#17]
the chrome-nfc.js lib can be use in Android phone(cca https://github.com/MobileChromeApps/mobile-chrome-apps) in order to communicate to the nfc ship ?

If yes, could you give the configuration .

**Comment by beaufortfrancois** [comment]
Since `chrome.usb` is not supported by Mobile Chrome Apps, chrome.nfc library won't work.
